import type { Metadata } from "next"
import "./globals.css"
import Header from "./components/layout/Header"
import Footer from "./components/layout/Footer"
import localFont from "next/font/local"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const stabilGroteskFont = localFont({
    src: [{
        path: "../../public/fonts/StabilGrotesk-Light.woff",
        weight: "300",
    }],
    variable: "--font-stabil",
})

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode,
}>) {
    return (
        <html lang="en" className={`${stabilGroteskFont.variable} font-sans font-light`}>
            <body>
                <Header />

                {children}

                <Footer />
            </body>
        </html>
    )
}
